### ISSUE TITLE
problem in DocGenerator

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#18]
```
Caused by: ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.appendParameter$priv$(DocGenerator.ceylon:1190)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.addParameters$priv$(DocGenerator.ceylon:1141)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDeclarationDoc$priv$(DocGenerator.ceylon:427)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDocumentationText(DocGenerator.ceylon:391)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getDocumentationText(EclipseDocGenerator.ceylon)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDocumentation$canonical$(DocGenerator.ceylon:170)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDocumentation(DocGenerator.ceylon:168)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getDocumentation$canonical$(EclipseDocGenerator.ceylon)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getDocumentation(EclipseDocGenerator.ceylon)
	at com.redhat.ceylon.eclipse.code.hover.DocumentationView.update(DocumentationView.java:259)
	at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.recomputeAnnotationsForSelection(MarkOccurrencesAction.java:297)
	at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.access$1000(MarkOccurrencesAction.java:51)
	at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction$1.run(MarkOccurrencesAction.java:573)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 24 more
```

**Comment by gavinking** [comment]
Let's assume this one is fixed now.
