### ISSUE TITLE
NPE due to incomplete initialization of ProjectPhasedUnit

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#25]
While abstracting `ExportModuleImportProposal` and testing it in Eclipse, I had the following error:

```
java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:377)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:312)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:301)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:377)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:263)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:343)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:63)
	at com.redhat.ceylon.eclipse.code.imports.eclipseModuleImportUtils_.getDescriptorPhasedUnit$priv$(eclipseModuleImportUtils.ceylon:86)
	at com.redhat.ceylon.eclipse.code.imports.eclipseModuleImportUtils_.getUnit(eclipseModuleImportUtils.ceylon:67)
	at com.redhat.ceylon.eclipse.code.imports.eclipseModuleImportUtils_.getUnit(eclipseModuleImportUtils.ceylon:53)
	at com.redhat.ceylon.ide.common.imports.AbstractModuleImportUtil.exportModuleImports(AbstractModuleImportUtil.ceylon:58)
	at com.redhat.ceylon.eclipse.code.correct.ExportModuleImportProposal.apply(ExportModuleImportProposal.java:49)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl.apply(AnnotationInformationControl.java:729)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl.access$500(AnnotationInformationControl.java:76)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$8.widgetSelected(AnnotationInformationControl.java:698)
```

This is due to the fact that the constructor of `ProjectPhasedUnit` calls `super()`, then stores the actual values for `$reified$xyz`, but the call to `super()` calls `createUnit()` which relies on those initialized type descriptors.

**Comment by bjansen** [comment]
Steps to reproduce: create a module and import for example `ceylon.net` without sharing it, then in run.ceylon create a shared toplevel declaration like

```ceylon
shared Endpoint ep = nothing;
```

Then call the quick fix to make the imported module `shared`.
