### ISSUE TITLE
bug in AddSatisfiesQuickFix

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#30]
I just go this one:

```
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.correct.AddSatisfiesQuickFix$impl$1anonymous_1_.visit(AddSatisfiesQuickFix.ceylon:371)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:76)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$BaseType.visit(Tree.java:2001)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkTypedDeclaration(Walker.java:307)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAnyAttribute(Walker.java:311)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAttributeDeclaration(Walker.java:315)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeDeclaration.visitChildren(Tree.java:1272)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:49)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:50)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:51)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeDeclaration.visit(Tree.java:1264)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:429)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBlock(Walker.java:434)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visitChildren(Tree.java:1817)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:68)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visit(Tree.java:1809)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkMethodDefinition(Walker.java:350)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visitChildren(Tree.java:1412)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:49)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:54)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:55)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visit(Tree.java:1404)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.ide.common.correct.AddSatisfiesQuickFix$impl.determineSatisfiedTypesTypeParams$priv$(AddSatisfiesQuickFix.ceylon:340)
	at com.redhat.ceylon.ide.common.correct.AddSatisfiesQuickFix$impl.determineMissingSatisfiedTypes$priv$(AddSatisfiesQuickFix.ceylon:299)
	at com.redhat.ceylon.ide.common.correct.AddSatisfiesQuickFix$impl.addSatisfiesProposals(AddSatisfiesQuickFix.ceylon:74)
	at com.redhat.ceylon.eclipse.code.correct.eclipseAddSatisfiesQuickFix_.addSatisfiesProposals(addSatisfiesQuickFix.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseAddSatisfiesQuickFix_.addSatisfiesProposals(addSatisfiesQuickFix.ceylon)
	at com.redhat.ceylon.ide.common.correct.IdeQuickFixManager.addQuickFixes(IdeQuickFixManager.ceylon:249)
	at com.redhat.ceylon.eclipse.code.correct.correctJ2C.addQuickFixes(correctJ2C.java:50)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:553)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:435)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

@bjansen would you take a look please?

**Comment by bjansen** [comment]
Is this one fixed @gavinking ?

**Comment by gavinking** [comment]
probably?
