### ISSUE TITLE
null value returned from native call (find subtypes)

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#32]
While trying to find subtypes of `ceylon.collection::Stack`:
```
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
        at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
        at com.redhat.ceylon.ide.common.util.FindSubtypesVisitor.visit(FindSubtypesVisitor.ceylon:38)
        at com.redhat.ceylon.compiler.typechecker.tree.Tree$ObjectExpression.visit(Tree.java:6954)
        at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkExpression(Walker.java:1373)
        at com.redhat.ceylon.compiler.typechecker.tree.Tree$Expression.visitChildren(Tree.java:6039)
        at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
        at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:169)
        at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:241)
        at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:285)
        at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:240)
```

**Comment by bjansen** [comment]
When this function is called:

```ceylon
    shared actual void visit(Tree.ObjectExpression that) {
        if (isRefinement(that.typeModel.declaration)) {
            declarationNodes.add(that);
        }
        
        super.visit(that);
    }
```

`that.typeModel` is `null`. @davidfestal is it possible that non-project source files are not typechecked?

**Comment by gavinking** [comment]
Should be fixed.
