### ISSUE TITLE
ModelError in DeltaBuilder

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#46]
I sometimes get this:

```
com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unsupported declaration type: class com.redhat.ceylon.model.typechecker.model.UnknownType
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1844)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1839)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:916)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorsForProducedTypes(Metamodel.java:953)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:875)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForArguments(Metamodel.java:1257)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:639)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:367)
	at ceylon.language.meta.typeLiteral_.typeLiteral(typeLiteral_.java:28)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder.hasStructuralChanges(deltaBuilder.ceylon:688)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$TopLevelDeclarationDeltaBuilder.calculateLocalChanges(deltaBuilder.ceylon:899)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:172)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$TopLevelDeclarationDeltaBuilder.buildDelta(deltaBuilder.ceylon:868)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$RegularCompilationUnitDeltaBuilder.manageChildDelta(deltaBuilder.ceylon:469)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:221)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$RegularCompilationUnitDeltaBuilder.buildDelta(deltaBuilder.ceylon:454)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildCompilationUnitDeltas$priv$(deltaBuilder.ceylon:117)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas$canonical$(deltaBuilder.ceylon:94)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas(deltaBuilder.ceylon:83)
	at com.redhat.ceylon.ide.common.model.ProjectSourceFile.buildDeltaAgainstModel(ProjectSourceFile.ceylon:123)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.searchForDependantFiles(CeylonBuilder.java:1476)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.calculateDependencies(CeylonBuilder.java:1331)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:991)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

One for you, @davidfestal.

**Comment by davidfestal** [comment]
dup of https://github.com/ceylon/ceylon-ide-common/issues/40

closing
