### ISSUE TITLE
Null check in `addConstructorQuickFix`

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-common#68]
```
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.correct.addConstructorQuickFix_.isExecutableStatement$priv$(AddConstructorQuickFix.ceylon:148)
	at com.redhat.ceylon.ide.common.correct.addConstructorQuickFix_.findLastExecutable$priv$(AddConstructorQuickFix.ceylon:123)
	at com.redhat.ceylon.ide.common.correct.addConstructorQuickFix_.addConstructorProposal(AddConstructorQuickFix.ceylon:41)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addQuickFixes(IdeQuickFixManager.ceylon:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.annotator.CeylonTypeCheckerAnnotator.addQuickFixes$priv$(CeylonTypeCheckerAnnotator.ceylon:162)
	at org.intellij.plugins.ceylon.ide.ceylonCode.annotator.CeylonTypeCheckerAnnotator.addAnnotation$priv$(CeylonTypeCheckerAnnotator.ceylon:123)
	at org.intellij.plugins.ceylon.ide.ceylonCode.annotator.CeylonTypeCheckerAnnotator.access$000(CeylonTypeCheckerAnnotator.ceylon:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.annotator.CeylonTypeCheckerAnnotator$1$1.$call$(CeylonTypeCheckerAnnotator.ceylon:190)
	at ceylon.collection.LinkedList.each(LinkedList.ceylon:683)
	at org.intellij.plugins.ceylon.ide.ceylonCode.annotator.CeylonTypeCheckerAnnotator$1.$call$(CeylonTypeCheckerAnnotator.ceylon:184)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:186)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:198)
	at org.intellij.plugins.ceylon.ide.ceylonCode.annotator.CeylonTypeCheckerAnnotator.annotate(CeylonTypeCheckerAnnotator.ceylon:183)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:135)

```

**Comment by bjansen** [comment]
I believe this has been fixed in a45c0bb60b137ac11a671377f24012849db0049b.
