### ISSUE TITLE
CME during completion

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#77]
Something to do with model loading, @davidfestal ?

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.redhat.ceylon.ide.common.completion.completionManager_.isTypeCaseOfSwitch$priv$(IdeCompletionManager.ceylon:1497)
	at com.redhat.ceylon.ide.common.completion.completionManager_.isCaseOfSwitch$priv$(IdeCompletionManager.ceylon:1409)
	at com.redhat.ceylon.ide.common.completion.completionManager_.isProposable$priv$(IdeCompletionManager.ceylon:1366)
	at com.redhat.ceylon.ide.common.completion.completionManager_.constructCompletions$priv$(IdeCompletionManager.ceylon:912)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals$canonical$(IdeCompletionManager.ceylon:282)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals(IdeCompletionManager.ceylon:108)
	at com.redhat.ceylon.eclipse.code.complete.CeylonCompletionProcessor$CompletionJob.run(CeylonCompletionProcessor.ceylon:159)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
Ah, I never had this one. Thanks to for your try.  Yes, that might be it. More precisely I think that might be related to the completion being run during a typechecking.

**Comment by davidfestal** [comment]
there's now the possibility of *limited* completion during the model udpate,

**Comment by gavinking** [comment]
Yeah great but I guess it means copying lists before iterating them.

**Comment by davidfestal** [comment]
exactly
