### ISSUE TITLE
Error in log: Failed to resolve org.intellij.plugins.ceylon.ide.psi.CeylonLocalAnalyzerManager$20$1anonymous_20_

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-common#96]
```
Failed to resolve org.intellij.plugins.ceylon.ide.psi.CeylonLocalAnalyzerManager$20$1anonymous_20_
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve org.intellij.plugins.ceylon.ide.psi.CeylonLocalAnalyzerManager$20$1anonymous_20_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1908)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1816)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:375)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1816)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.addLocalDeclarations(AbstractModelLoader.java:3408)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:3198)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$1100(AbstractModelLoader.java:103)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$16.run(AbstractModelLoader.java:2515)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:399)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:375)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:396)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2511)
	at com.redhat.ceylon.model.loader.model.LazyClass$1.run(LazyClass.java:97)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:399)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:375)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:396)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:91)
	at com.redhat.ceylon.model.loader.model.LazyClass.getParameterLists(LazyClass.java:176)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForArguments(Metamodel.java:1293)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:655)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:371)
	at ceylon.language.meta.typeLiteral_.typeLiteral(typeLiteral_.java:30)
	at org.intellij.plugins.ceylon.ide.psi.analyzerManagerClass_.<clinit>(CeylonFile.ceylon:97)
	at org.intellij.plugins.ceylon.ide.psi.CeylonFile.getLocalAnalyzer(CeylonFile.ceylon:174)
	at org.intellij.plugins.ceylon.ide.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.ceylon:83)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:836)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:515)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:472)
	at com.intellij.codeInsight.folding.impl.OffsetsElementSignatureProvider.restoreBySignatureTokens(OffsetsElementSignatureProvider.java:94)
	at com.intellij.codeInsight.folding.impl.AbstractElementSignatureProvider.restoreBySignature(AbstractElementSignatureProvider.java:74)
	at com.intellij.codeInsight.folding.impl.GenericElementSignatureProvider.restoreBySignature(GenericElementSignatureProvider.java:51)
	at com.intellij.codeInsight.folding.impl.FoldingPolicy.restoreBySignature(FoldingPolicy.java:72)
	at com.intellij.codeInsight.folding.impl.FoldingPolicy.restoreBySignature(FoldingPolicy.java:51)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.lambda$readExternal$0(DocumentFoldingInfo.java:306)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:879)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:283)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:360)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:68)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.parseEntry(HistoryEntry.java:220)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.createHeavy(HistoryEntry.java:121)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager$3.run(EditorHistoryManager.java:310)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:344)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:336)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:175)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$5(ProjectManagerImpl.java:343)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment]
It's actually due to https://github.com/ceylon/ceylon/issues/6840#issuecomment-276005875 that was reopened this morning.

**Comment by bjansen** [comment]
Closing, because the original issue is also closed.
